config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: %i[new create destroy]

  resources :projects, only: %i[create edit update show destroy index new]

  resources :projects, shallow: true do
    resources :tasks, path: 'project_tasks' do
      member do
        patch :complete
      end
    end
  end
  resources :tasks do
    put :sort, on: :collection
  end

  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/task.rb
class Task < ActiveRecord::Base
  require 'date'
  belongs_to :project
  validates :title, presence: true
  default_scope { order('position ASC') }

  def completeda?
    complete == true
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  require 'date'
  before_action :set_project, only: %i[new create index edit update]
  after_action :update_priority, only: [:destroy]
  respond_to :html, :js

  def update_priority
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks
    i = @deleted_position

    @tasks[(@deleted_position - 1)..-1].each do |n|
      n.update_attributes(position: i)
      i += 1
    end
  end

  def new
    @task = @project.tasks.new
  end

  def show
    @tasks = @project.tasks
  end

  def create
    @task = @project.tasks.scope.build(task_params)
    respond_to do |format|
      if @task.save
        @tasks = @project.tasks
        @previous_position = @tasks.length
        @task.update_attributes(position: @previous_position)
        format.html { redirect_to root_url }
        format.js
        format.json do
          render action: 'show',
                 status: :created, location: @task
        end
      else
        format.html { render action: 'new' }
        format.json do
          render json: @task.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def update
    @task = @project.tasks.find(params[:id])
    deadline = task_deadline(params[:deadline])
    respond_to do |format|
      if @task.update(title: params[:title], priority: params[:priority], deadline: deadline)
        format.html { redirect_to root_url }
        format.js
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    @deleted_position = @task.position
    @task.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  def complete
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
    if @task[:complete] == false
      @task.update_attribute(:complete, true)
    else
      @task.update_attribute(:complete, false)
    end
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  def sort
    params[:order].each do |_key, value|
      Task.find(value[:id]).update_attribute(:position, value[:position])
    end
    render nothing: true
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_deadline(deadline)
    deadline = if deadline != ''
                 DateTime.strptime(deadline, '%m/%d/%Y  %H:%M %p')
               end
  end

  def task_params
    task = params[:task].permit(:title, :priority, :deadline)
    task[:deadline] = task_deadline(task[:deadline])
    task
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def create_task
    project = Project.find(params[id])
    @task = project.tasks.build
  end
end

app/views/tasks/_edit.html.erb
<%= javascript_include_tag 'tasks/edit', 'data-turbolinks-track' => true  %>

<%= form_tag task_path(id: @task, project_id: @project), method: "put", remote: true%>
<%= text_field_tag :title, @task.title %>
<td><div class="star-priority" data-score= <%= @task.priority %>></div></td>
<td><div id="star-priority" data-score= <%= @task.priority %>></div></td>
<% require 'date'%>
<div class='input-group date' id='datetimepicker1'>
  <% if !@task.deadline.nil? %>
      <%= text_field_tag :deadline, @task.deadline.strftime("%d-%m-%Y  %H:%M %p"), class: 'form-control'%>
  <% else %>
      <%= text_field_tag :deadline, @task.deadline, class: 'form-control'%>
  <% end %>
  <span class="input-group-addon">
    <span class="glyphicon glyphicon-calendar"></span>
  </span>
</div>
<%= submit_tag "Save", class: "btn btn-primary" %>

app/views/tasks/_form.html.erb
<%= javascript_include_tag 'tasks/task_form', 'data-turbolinks-track' => true  %>
<%= javascript_include_tag 'tasks/star_priority_form', 'data-turbolinks-track' => true  %>




  <div class="new_form">
<%= form_for(Task.new,  remote: true, :html => {:id => "form#{project.id}"}) do |f| %>
        <%= hidden_field_tag :project_id,project.id%>
        <div class="col-xs-5">
        <%= f.text_field :title, class:'input_'%>
        </div>
        <div class="col-xs-2">
    <div class="star-priority-new" id="star-priority-new<%=@project.id %>"></div>
        </div>
        <div class="col-xs-3">
    <div class='input-group date datetimepicker1'>
      <%= f.text_field :deadline, class: 'form-control' %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
        </div>
        <div class="col-xs-2">
  <%= f.submit 'Add Task',:class => "btn btn-success"                           %>
        </div>
<% end %>
</div>

app/views/tasks/_task.html.erb
<%= javascript_include_tag 'tasks/star_priority_show', 'data-turbolinks-track' => true  %>
<%= javascript_include_tag 'tasks/drag&drop', 'data-turbolinks-track' => true  %>
<%= javascript_include_tag 'tasks/tasks', 'data-turbolinks-track' => true  %>

<div  id="row_<%=task.id %>" data-id="<%= task.id %>">
  <div class="row">
    <div class="complete">
      <% if task.completeda? %>

          <div class="col-xs-1 col-sm-1">
            <%=link_to complete_task_path(project_id: project, id: task), remote: true, method: :patch do%>
                <input id="#check_<%=task.id%>" type="checkbox" checked/>
            <% end %>
          </div>

          <div class="<%= task.id %> col-xs-4 col-sm-4">
            <%= task.title%>
          </div>

      <% else %>
          <div class="col-xs-1 col-sm-1">
            <%=link_to complete_task_path(:project_id => project , :id => task), remote: true, method: :patch do%>
                <input id="#check_<%=task.id%>" type="checkbox"/>
            <% end %>
          </div>

          <div class="<%= task.id %> col-xs-4 col-sm-4">
            <%= task.title%>
          </div>

      <% end %>

      <div class="col-xs-2 col-sm-2">
        <div class="star-priority" data-score= <%= task.priority %>></div>
      </div>

      <div class="col-xs-3 col-sm-3">
        <% require 'date'%>
        <% if !task.deadline.nil? %>
            <%= task.deadline.strftime("%d-%m-%Y  %H:%M %p") %>
        <% else %>
            <%= 'someday:)' %>
        <% end %>
      </div>

      <div class="col-xs-2 col-sm-2">
        <span class="trash">
          <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, task_path(:project_id => project , :id => task), remote: true,
                          method: :delete,
                          data: {confirm: 'Are you sure?'} %>
        </span>

        <span class="update">
          <%=link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_task_path(:project_id => project , :id => task), remote: true%>
        </span>

      </div>
    </div>
  </div>
</div>

app/views/tasks/complete.js.erb
$("#tasks_<%=@project.id %>").html("<%= j( render partial: 'tasks/task', collection: @project.tasks, :locals => {:project => @project})%>");

app/views/tasks/create.js.erb
$("#tasks_<%=@project.id %>").html("<%= j( render partial: 'tasks/task', collection: @project.tasks, :locals => {:project => @project})%>");
$("#form<%=@project.id %>")[0].reset();

app/views/tasks/destroy.js.erb
$("#row_<%=@task.id %>").remove();

app/views/tasks/edit.js.erb
$("#row_<%=@task.id %>").hide();
$("#row_<%=@task.id %>").after("<%= j render 'tasks/edit'%>");

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <li><%= task.title %></li>
  <p>sdfesf</p>
  <h1><%= link_to "New", new_todo_path %></h1>
<% end %>

app/views/tasks/new.js.erb
$('#task-form-<%= @project.id %>').html("<%= j (render 'tasks/form') %>");
$('#task-form-<%= @project.id %>').slideDown(350)

app/views/tasks/update.js.erb
$("#tasks_<%=@project.id %>").html("<%= j( render partial: 'tasks/task', collection: @project.tasks, :locals => {:project => @project})%>");
$("#task-form-<%=@project.id %>").slideUp(350);