config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: %i[new create destroy]

  resources :projects, only: %i[create edit update show destroy index new]

  resources :projects, shallow: true do
    resources :tasks, path: 'project_tasks' do
      member do
        patch :complete
      end
    end
  end
  resources :tasks do
    put :sort, on: :collection
  end

  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  default_scope -> { order('created_at') }
  validates :user_id, presence: true
  validates :title, presence: true
  accepts_nested_attributes_for :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :signed_in_user, only: %i[create destroy index update]
  before_action :correct_user, only: %i[index edit update destroy create]
  before_action :all_projects, only: %i[create update destroy]
  respond_to :html, :js

  def index
    @projects = current_user.projects
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    @project = Project.new
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js { }
    end
  end

  def create
    @project = current_user.projects.build(project_params)
    @project.save
    respond_to do |format|
        format.html { redirect_to root_url }
        format.js
      end
  end

  def update
    respond_to do |format|
      if @project.update_attributes(project_params)
        format.html { redirect_to @project, notice: 'Student was successfully updated.' }
        format.json { respond_with_bip(@project) }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
      format.js   { render layout: false }
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  private

  def all_projects
    @projects = current_user.projects.all
  end

  def all_taskts
    @tasks = @project.tasks.all
  end

  def project_params
    params.require(:project).permit(:title)
  end

  def correct_user
    @project = current_user.projects.find_by(id: params[:id])
  end
end

app/views/projects/_form.html.erb
<div class="panel panel-primary ">
  <div class="panel-heading ">

  <%=form_for @project, remote: true do |f| %>

      <%= f.text_field :title, :class=>'betaTextField'%>

      <%= f.button 'Create project', :class=>'btn btn-success'%>

  <% end %>
</div>
  </div>
</div>

app/views/projects/_index.html.erb
<div class="row">
  <div class="" id="projects"><%= render partial: 'projects/project', collection: @projects%>
  </div>
</div>


<div class="row">
  <div class="create_new_project" id="project-form"  style="display:none;"></div>
</div>

  <div class="text-center">
    <%= link_to new_project_path,
                data: {no_turbolink: true, remote: true} do %>
      <button class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i>Add TODO List</button>
    <% end %>
  </div>

app/views/projects/_project.html.erb
<%= javascript_include_tag 'project/sortable_project_tasks', 'data-turbolinks-track' => true  %>
<%= javascript_include_tag 'tasks/task_form' %>

<%= javascript_include_tag 'tasks/star_priority_form'%>
<div>
  <div id="panel-group_<%= project.id %>">
      <div class="panel panel-primary ">
            <div class="panel-heading ">
                  <span class="glyphicon glyphicon-calendar vcenter"></span><%= best_in_place project, :title, :classes => 'name-edit'%></td>
                  <div align="right">
                    <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, project, remote: true,
                                  class: 'btn btn-primary btn-xs',
                                  method: :delete,
                                  data: {confirm: 'Are you sure?'} %>
                  </div>
            </div>
        <div class="panel-body">
<div id="task-form-<%= @project.id%>" class="row">
          <%= render partial: 'tasks/form', :locals => {:project => project} %>
</div>
          <table class="tasks">
          <tr>  <div class="sortable" id="tasks_<%= project.id %>">
              <%= render partial: 'tasks/task', collection: project.tasks, :locals => {:project => project} %>
            </div>
          </tr>
          </table>



        </div>
      </div>

</td>
</div>

</div>
</tr>

app/views/projects/_show.html.erb
<%= form_for [@project, @project.tasks.build] do |f|   %>
<%= f.text_field :title %>
  <%= f.button :submit                           %>
<% end %>

app/views/projects/destroy.js.erb
$("#panel-group_<%=@project.id %>").remove();

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-5 col-md-offset-1">
    <h2>Tasks</h2>
  </div>

  <div class="col-md-2 col-md-offset-4">
    <%= link_to new_project_path, remote: true do %>
      <button class="btn btn-default">New</button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-2" id="project-form" style="display:none;"></div>
</div>

<div class="row">
  <div class="col-md-7 col-md-offset-1" id="projects"><%= render partial: 'projects/project', collection: @projects %>
  </div>
</div>

app/views/projects/new.js.erb
$('#project-form').html("<%= j (render 'projects/form') %>");
$('#project-form').slideDown(350);